@baseUrl = http://localhost:3001
@email = han.jimin@example.com
@password = test1234!
@role = CUSTOMER

// 테스틀 위해 준비한 계정으로 우선 로그인을 합니다.
###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}"
}


###
GET {{baseUrl}}/reviews/me?page=1&pageSize=10&hasReview=false

###
GET {{baseUrl}}/reviews/mover/10000000-0000-4000-8000-000000000001
###
POST {{baseUrl}}/reviews
content-type: application/json

{
  "estimateId": "40000000-0000-4000-8000-000000000013",
  "content": "기사님이 너무 친절하셨어요. 짐도 안전하게 잘 옮겨주셨습니다.",
  "rating": 5
}

